create combined fwbundle in build-fw and use it in hardware-long

diff --git a/.github/workflows/hardware-long.yml b/.github/workflows/hardware-long.yml
--- a/.github/workflows/hardware-long.yml
+++ b/.github/workflows/hardware-long.yml
@@ -96,60 +96,52 @@ jobs:
           maturin build --release
           pip install ../../target/wheels/*
 
-      - name: Generate board names
-        shell: bash
-        run: |
-          case "${{ matrix.config.board }}" in
-            p100) SMC_BOARD=tt_blackhole@p100/tt_blackhole/smc;;
-            p100a) SMC_BOARD=tt_blackhole@p100a/tt_blackhole/smc;;
-            p150a) SMC_BOARD=tt_blackhole@p150a/tt_blackhole/smc;;
-            *) echo "Unknown board: ${{ matrix.config.board }}"; exit 1;;
-          esac
-          case "${{ matrix.config.board }}" in
-            p100) BMC_BOARD=tt_blackhole@p100/tt_blackhole/bmc;;
-            p100a) BMC_BOARD=tt_blackhole@p100a/tt_blackhole/bmc;;
-            p150) BMC_BOARD=tt_blackhole@p150/tt_blackhole/bmc;;
-            p300) BMC_BOARD=p300/tt_blackhole/bmc;;
-            *) echo "Unknown board: ${{ matrix.config.board }}"; exit 1;;
-          esac
-          echo "SMC_BOARD=$SMC_BOARD" >> "$GITHUB_ENV"
-          echo "BMC_BOARD=$BMC_BOARD" >> "$GITHUB_ENV"
-
-      - name: Select existing firmware bundle
-        run: |
-          case "${{ matrix.config.board }}" in
-            p100) FW_PATH=firmware/p100.fwbundle;;
-            p100a) FW_PATH=firmware/p100a.fwbundle;;
-            p150a) FW_PATH=firmware/p150a.fwbundle;;
-            *) echo "Unknown board type"; exit 1;;
-          esac
-          echo "FW_PATH=$FW_PATH" >> $GITHUB_ENV
+      # - name: Generate board names
+      #   shell: bash
+      #   run: |
+      #     case "${{ matrix.config.board }}" in
+      #       p100) SMC_BOARD=tt_blackhole@p100/tt_blackhole/smc;;
+      #       p100a) SMC_BOARD=tt_blackhole@p100a/tt_blackhole/smc;;
+      #       p150a) SMC_BOARD=tt_blackhole@p150a/tt_blackhole/smc;;
+      #       *) echo "Unknown board: ${{ matrix.config.board }}"; exit 1;;
+      #     esac
+      #     case "${{ matrix.config.board }}" in
+      #       p100) BMC_BOARD=tt_blackhole@p100/tt_blackhole/bmc;;
+      #       p100a) BMC_BOARD=tt_blackhole@p100a/tt_blackhole/bmc;;
+      #       p150) BMC_BOARD=tt_blackhole@p150/tt_blackhole/bmc;;
+      #       p300) BMC_BOARD=p300/tt_blackhole/bmc;;
+      #       *) echo "Unknown board: ${{ matrix.config.board }}"; exit 1;;
+      #     esac
+      #     echo "SMC_BOARD=$SMC_BOARD" >> "$GITHUB_ENV"
+      #     echo "BMC_BOARD=$BMC_BOARD" >> "$GITHUB_ENV"
 
       - name: Flash Firmware
         working-directory: zephyr
         run: |
-          # This needs to be added to the github runner
-          export PATH=$PATH:/opt/SEGGER/JLink/
+          tar -xvf ../combined-fwbundle.tar
+          tt-flash --fw-tar fw_pack*.fwbundle --force
+          # # This needs to be added to the github runner
+          # export PATH=$PATH:/opt/SEGGER/JLink/
 
-          cp $FW_PATH /opt/tenstorrent/fw/stable/
+          # cp $FW_PATH /opt/tenstorrent/fw/stable/
 
-          # TODO: ideally we would use one twister command to build and
-          # flash BMC and SMC firmware, but since each chip uses a separate
-          # debug adapter this doesn't work. For now, just flash BMC
-          # then run twister with SMC firmware
-          ./scripts/twister -i --retry-failed 3 \
-            --retry-interval 5 \
-            --tag e2e \
-            -p $BMC_BOARD --device-testing \
-            --hardware-map /opt/tenstorrent/twister/hw-map.yml --west-flash \
-            -T ../tt-zephyr-platforms/app -ll DEBUG
-          # Run E2E test to verify BMC and SMC firmware boot, and that
-          # the SMC firmware sets up PCIe and ARC messages
-          ./scripts/twister -i --retry-failed 3 \
-            -p $SMC_BOARD --device-testing \
-            --tag e2e \
-            --hardware-map /opt/tenstorrent/twister/hw-map.yml --west-flash \
-            -T ../tt-zephyr-platforms/app -ll DEBUG
+          # # TODO: ideally we would use one twister command to build and
+          # # flash BMC and SMC firmware, but since each chip uses a separate
+          # # debug adapter this doesn't work. For now, just flash BMC
+          # # then run twister with SMC firmware
+          # ./scripts/twister -i --retry-failed 3 \
+          #   --retry-interval 5 \
+          #   --tag e2e \
+          #   -p $BMC_BOARD --device-testing \
+          #   --hardware-map /opt/tenstorrent/twister/hw-map.yml --west-flash \
+          #   -T ../tt-zephyr-platforms/app -ll DEBUG
+          # # Run E2E test to verify BMC and SMC firmware boot, and that
+          # # the SMC firmware sets up PCIe and ARC messages
+          # ./scripts/twister -i --retry-failed 3 \
+          #   -p $SMC_BOARD --device-testing \
+          #   --tag e2e \
+          #   --hardware-map /opt/tenstorrent/twister/hw-map.yml --west-flash \
+          #   -T ../tt-zephyr-platforms/app -ll DEBUG
       - name: Install TT-SMI and reset the device
         run: |
           sed -i -e 's/http/https/g' /etc/apt/sources.list
