ci: workflows: reformat to satisfy yamllint
Reformat the workflows files to satisfy yamllint checker

Signed-off-by: Daniel DeGrasse <ddegrasse@tenstorrent.com>

diff --git a/.github/workflows/license-check.yml b/.github/workflows/license-check.yml
--- a/.github/workflows/license-check.yml
+++ b/.github/workflows/license-check.yml
@@ -14,28 +14,28 @@ jobs:
     runs-on: ubuntu-22.04
     name: Scan code for licenses
     steps:
-    - name: Checkout the code
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
-    - name: Scan the code
-      id: scancode
-      uses: zephyrproject-rtos/action_scancode@v4
-      with:
-        directory-to-scan: 'scan/'
-    - name: Artifact Upload
-      uses: actions/upload-artifact@v4
-      with:
-        name: scancode
-        path: ./artifacts
+      - name: Checkout the code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Scan the code
+        id: scancode
+        uses: zephyrproject-rtos/action_scancode@v4
+        with:
+          directory-to-scan: 'scan/'
+      - name: Artifact Upload
+        uses: actions/upload-artifact@v4
+        with:
+          name: scancode
+          path: ./artifacts
 
-    - name: Verify
-      run: |
-        if [ -s ./artifacts/report.txt ]; then
-          report=$(cat ./artifacts/report.txt)
-          report="${report//'%'/'%25'}"
-          report="${report//$'\n'/'%0A'}"
-          report="${report//$'\r'/'%0D'}"
-          echo "::error file=./artifacts/report.txt::$report"
-          exit 1
-        fi
+      - name: Verify
+        run: |
+          if [ -s ./artifacts/report.txt ]; then
+            report=$(cat ./artifacts/report.txt)
+            report="${report//'%'/'%25'}"
+            report="${report//$'\n'/'%0A'}"
+            report="${report//$'\r'/'%0D'}"
+            echo "::error file=./artifacts/report.txt::$report"
+            exit 1
+          fi
